# Generated by sila2.code_generator; sila2.__version__: 0.13.0

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.densorc8control_impl import DensoRC8ControlImpl
from .generated.densorc8control import DensoRC8ControlFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        # Defaults
        if name is None:
            name = "DensoRC8"
        if description is None:
            description = "SiLA 2 Server for Denso RC8 using bcapclient"
        if server_uuid is None:
            # Default-UUID (can be overwritten via CLI)
            server_uuid = UUID("78e7306b-4aef-4c70-857c-87e0d2f4e32f")

        super().__init__(
            server_name=name,
            server_description=description,
            server_type="RobotController",
            server_version="1.0.0",
            server_vendor_url="https://www.densorobotics-europe.com/",
            server_uuid=server_uuid,
        )

        # Feature registrieren
        self.densorc8control = DensoRC8ControlImpl(self)
        self.set_feature_implementation(DensoRC8ControlFeature, self.densorc8control)
